version: '3.4'

services:
    mongo:
        image: mongo:latest
        restart: unless-stopped
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root  
            MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
        networks:
            - bridge-network
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - "27017:27017"
            
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: renatogroffe
            ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
        links:
            - mongo
        networks:
            - bridge-network
        

volumes:
  mongodb:
  mongodb_config:
          
          
networks: 
  bridge-network:
    driver: bridge
