version: "3.4"

services:
  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IDENTITYSERVICE_URLS=http://localhost:80
      - ConnectionString=Server=sql.data;Database=NoahidentityDb;MultipleActiveResultSets=true;User Id=sa;Password=!QAZxsw2#EDC;
      - ApiURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:10001
      - FrontendURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:8002
    ports:
      - "8000:80"

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WEBAPI_URLS=http://+:80
      - IdentityServerURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:8000
      - FrontendURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:8002

      - MONGODB_HOST=mongo
      - MONGODB_DATABASE=noah_db
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=MongoDB2020!

      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=noah
      - INFLUXDB_PASSWORD=Confitec123
      - INFLUXDB_USESSL=false
      - INFLUXDB_DATABASE=noah_db
    ports:
      - "10001:80"

  noah.spa:
    environment:
      - production=false
      - IdentityServerURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:8000
      - ApiURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:10001
      - FrontendURI=http://${NOAH_EXTERNAL_DNS_NAME_OR_IP}:8002
    ports:
      - "8002:80"

  backgroundservice:
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_DATABASE=noah_db
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=MongoDB2020!

      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=noah
      - INFLUXDB_PASSWORD=Confitec123
      - INFLUXDB_USESSL=false
      - INFLUXDB_DATABASE=noah_db

      - SENSOR_INTERVAL_SIGNAL=300000 

      - MQTT_HOSTNAME=mosquitto
      - MQTT_PORT=1883

  sql.data:
    environment:
      - SA_PASSWORD=!QAZxsw2#EDC
      - ACCEPT_EULA=Y
    # ports:
      # - "1433:1433"

  influxdb:
    environment:
      - INFLUXDB_DB=noah_db
      - INFLUXDB_ADMIN_USER=noah
      - INFLUXDB_ADMIN_PASSWORD=Confitec123
    # ports:
      # - "8086:8086"

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MongoDB2020!
    # ports:
      # - "27017:27017"

  mongo.express:
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=noah
      - ME_CONFIG_BASICAUTH_PASSWORD=MongoExpress2020!
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=MongoDB2020!
    ports:
      - "8081:8081"

  portainer:
    ports:
      - 9000:9000

  mosquitto:
    ports:
      - "1883:1883"
